[{
    "id": "acaa1683.344b78",
    "type": "ibmiot in",
    "z": "80bb9cd7.6337a",
    "authentication": "boundService",
    "apiKey": "",
    "inputType": "evt",
    "logicalInterfaceId": "",
    "ruleId": "",
    "deviceId": "senb827eb3e3f29",
    "applicationId": "",
    "deviceType": "sensehatDEV",
    "eventType": "+",
    "commandType": "",
    "format": "json",
    "name": "IBM IoT",
    "service": "registered",
    "allDevices": false,
    "allApplications": "",
    "allDeviceTypes": false,
    "allEvents": true,
    "allCommands": "",
    "allFormats": "",
    "qos": 0,
    "x": 90,
    "y": 160,
    "wires": [
        ["5ce9f25a.34a8bc"]
    ]
}, {
    "id": "5ce9f25a.34a8bc",
    "type": "function",
    "z": "80bb9cd7.6337a",
    "name": "setScreenStatus",
    "func": "var localReceivedTemperature = msg.payload.d.temperature;\n\nvar obtainedPreviousGlobalScreenStatus = global.get(\"globalScreenStatus\");\n\nif (localReceivedTemperature > 29.0){\n    if(obtainedPreviousGlobalScreenStatus==\"off\"){\n        global.set(\"globalScreenStatus\", \"on\");\n        \n        global.set(\"globalSend\", \"true\");\n        msg.deviceId = \"b827eb3e3f29\";\n        msg.deviceType = \"raspberryGW\";\n        msg.payload = {\"screen\":\"on\"};\n        return msg;\n    }\n    global.set(\"globalScreenStatus\", \"on\");\n}\n\n\n\nif (localReceivedTemperature < 29.0){\n    if(obtainedPreviousGlobalScreenStatus==\"on\"){\n        global.set(\"globalScreenStatus\", \"off\");\n        \n        global.set(\"globalSend\", \"true\");\n        msg.deviceId = \"b827eb3e3f29\";\n        msg.deviceType = \"raspberryGW\";\n        msg.payload = {\"screen\":\"off\"};\n        return msg;\n    }\n    global.set(\"globalScreenStatus\", \"off\");\n}\n",
    "outputs": 1,
    "noerr": 0,
    "x": 320,
    "y": 160,
    "wires": [
        ["26eeee8e.411692", "215d47bd.6366a8"]
    ]
}, {
    "id": "26eeee8e.411692",
    "type": "debug",
    "z": "80bb9cd7.6337a",
    "name": "",
    "active": true,
    "tosidebar": true,
    "console": true,
    "tostatus": true,
    "complete": "payload",
    "x": 580,
    "y": 220,
    "wires": []
}, {
    "id": "215d47bd.6366a8",
    "type": "ibmiot out",
    "z": "80bb9cd7.6337a",
    "authentication": "boundService",
    "apiKey": "",
    "outputType": "cmd",
    "deviceId": "b827eb3e3f29",
    "deviceType": "raspberryGW",
    "eventCommandType": "display",
    "format": "json",
    "data": "{}",
    "qos": 0,
    "name": "IBM IoT",
    "service": "registered",
    "x": 600,
    "y": 160,
    "wires": []
}]